name: "Deploy"
on:
  workflow_dispatch:

jobs:
  build_and_release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v2

      - name: Setup Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
        with:
          install: true

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: hoersamu
          password: ${{ secrets.CI_PERSONAL_TOKEN }}

      - name: Build and push to Docker registries
        id: docker_build
        uses: docker/build-push-action@v3
        with:
          context: ./
          platforms: linux/amd64
          file: ./Dockerfile
          push: true
          tags: |
            hoersamu/tacmaps:latest
            ghcr.io/hoersamu/tacmaps:latest

      - name: Invoke deployment hook
        uses: distributhor/workflow-webhook@v3
        env:
          webhook_url: ${{ secrets.DEPLOY_WEBHOOK }}
          webhook_secret: ${{ secrets.DEPLOY_SECRET }}
          silent: true
